name: CI
on: [push, pull_request]

env:
  PRIVATE_KEY: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80

jobs:
  build:
    name: Build, lint, and test
    runs-on: ubuntu-latest

    steps:
      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build
        run: nix-shell --run build-sdk2

      - name: Lint
        run: nix-shell --run lint-sdk

      - name: Test
        run: nix-shell --run test-sdk
